# Generated by Django 4.1.7 on 2023-05-16 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_teammember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='position',
        ),
    ]
